package com.chatop.backend.service;

import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import com.chatop.backend.model.DAOUser;
import com.chatop.backend.repository.UserRepository;

import lombok.Data;

@Data
@Service
public class UserService {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;


    public Optional<DAOUser> getUser(final Integer id) {
        return userRepository.findById(id);
    }

    public Iterable<DAOUser> getUsers() {
        return userRepository.findAll();
    }

    public void deleteUser(final Integer id) {
        userRepository.deleteById(id);
    }

    public DAOUser saveUser(DAOUser user) {
        DAOUser savedUser = userRepository.save(user);
        return savedUser;
    }

}